import { Ingredient } from "../../types/entities";
import { RecipeWithAuthor } from "../../types/relations";
import { singleUser } from "./users";

const ingredients: Ingredient[] = [
  { name: "rice", amount: 2, unit: "cups", unitShort: "cups" },
  { name: "vegetable oil", amount: 2, unit: "tablespoons", unitShort: "tbsp" },
  { name: "chicken breast", amount: 1, unit: "piece", unitShort: "pcs" },
  { name: "carrot", amount: 1, unit: "piece", unitShort: "pcs" },
  { name: "spring onion", amount: 2, unit: "stalks", unitShort: "stalks" },
  { name: "egg", amount: 1, unit: "piece", unitShort: "pcs" },
];

export const recipesSeeder: RecipeWithAuthor[] = [
  {
    id: "b1cbeeb6-6672-4ccd-98ff-bb78381d5926",
    title: "Home-made Nasi Goreng",
    description: "Sayur koooolll sayur kooolll",
    imageUrl:
      "https://cdn1-production-images-kly.akamaized.net/EjwV7j3Y4JrlqUFuavke4NtRWtM=/1200x675/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/3108566/original/079979700_1587487794-Sajiku_1.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    authorId: "b1cbeeb6-6672-4ccd-98ff-bb78381d5926",
    dairyFree: true,
    glutenFree: false,
    healthy: false,
    price: 12000,
    servings: 1,
    sustainable: false,
    vegan: false,
    vegetarian: false,
    cookDuration: 12,
    ingredients: JSON.stringify(ingredients),
    likesCount: 1200,
    author: singleUser,
  },
  {
    id: "c9f6c4a2-9d3d-45a3-93f8-6f4a35ff6241",
    title: "Chicken Fried Rice",
    description: "A delicious and easy-to-make chicken fried rice recipe.",
    imageUrl:
      "https://cdn1-production-images-kly.akamaized.net/EjwV7j3Y4JrlqUFuavke4NtRWtM=/1200x675/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/3108566/original/079979700_1587487794-Sajiku_1.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    authorId: "c9f6c4a2-9d3d-45a3-93f8-6f4a35ff6241",
    dairyFree: true,
    glutenFree: false,
    healthy: false,
    price: 15000,
    servings: 2,
    sustainable: false,
    vegan: false,
    vegetarian: false,
    cookDuration: 20,
    ingredients: JSON.stringify(ingredients),
    likesCount: 800,
    author: singleUser,
  },
  {
    id: "a0b9c8d7-e6f5-4a3b-9c2d-1b0a9c8d7e6f",
    title: "Classic Spaghetti Bolognese",
    description:
      "A classic spaghetti Bolognese recipe with rich tomato sauce and flavorful ground beef.",
    imageUrl:
      "https://cdn1-production-images-kly.akamaized.net/EjwV7j3Y4JrlqUFuavke4NtRWtM=/1200x675/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/3108566/original/079979700_1587487794-Sajiku_1.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    authorId: "a0b9c8d7-e6f5-4a3b-9c2d-1b0a9c8d7e6f",
    dairyFree: false,
    glutenFree: false,
    healthy: false,
    price: 18000,
    servings: 4,
    sustainable: false,
    vegan: false,
    vegetarian: false,
    cookDuration: 30,
    ingredients: JSON.stringify(ingredients),
    likesCount: 1600,
    author: singleUser,
  },
  {
    id: "d0e1f2a3-b4c5-6d7e-8f9a-0b1c2d3e4f5a",
    title: "Herb Roasted Chicken with Vegetables",
    description:
      "Tender and juicy roasted chicken with potatoes, carrots, and aromatic herbs.",
    imageUrl:
      "https://cdn1-production-images-kly.akamaized.net/EjwV7j3Y4JrlqUFuavke4NtRWtM=/1200x675/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/3108566/original/079979700_1587487794-Sajiku_1.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    authorId: "d0e1f2a3-b4c5-6d7e-8f9a-0b1c2d3e4f5a",
    dairyFree: true,
    glutenFree: true,
    healthy: true,
    price: 22000,
    servings: 4,
    sustainable: false,
    vegan: false,
    vegetarian: false,
    cookDuration: 60,
    ingredients: JSON.stringify(ingredients),
    likesCount: 2000,
    author: singleUser,
  },
  {
    id: "d0e1f2a3-b4c5-6d7e-8f9a-1a1c2d3e4f5x",
    title: "Herb Roasted Chicken with Vegetables",
    description:
      "Tender and juicy roasted chicken with potatoes, carrots, and aromatic herbs.",
    imageUrl:
      "https://cdn1-production-images-kly.akamaized.net/EjwV7j3Y4JrlqUFuavke4NtRWtM=/1200x675/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/3108566/original/079979700_1587487794-Sajiku_1.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    authorId: "d0e1f2a3-b4c5-6d7e-8f9a-0b1c2d3e4f5a",
    dairyFree: true,
    glutenFree: true,
    healthy: true,
    price: 22000,
    servings: 4,
    sustainable: false,
    vegan: false,
    vegetarian: false,
    cookDuration: 60,
    ingredients: JSON.stringify(ingredients),
    likesCount: 2000,
    author: singleUser,
  },
];
